### ISSUE TITLE
As a AirViewer2 user I want to set password for the pdf file, so that I can protect information in the files.

### ISSUE THREAD

**Issue by pajayreddy** [Team-AVT/AirViewer2#46]
## Todo
- [ ] Write a class with a method to set a password for the existing pdf.
- [ ] Write Test cases to evaluate the working of the set password method and provide code coverage
- [ ] setting a User Interface button for the password setup, On clicking it, opens a dialogue box that asks the users to enter a password.
